module.exports = [
	// {
	// 	type: 'blog post',
	// 	title: 'Build your own React',
	// 	description:
	// 		'We are going to rewrite React from scratch. Step by step. Following the architecture from the real React code...',
	// 	date: '2019/11/13',
	// 	url: '/build-your-own-react',
	// 	pinned: true,
	// },
	// {
	// 	type: 'blog post',
	// 	title: 'React',
	// 	description: '',
	// 	date: '2021/7/11',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: 'javascript那些遍历的方法',
	// 	description: '如果只谈性能，显然是 for > forEach > map',
	// 	date: '2021/2/10',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: '解决github不显示图片',
	// 	description: '配置相关host',
	// 	date: '2021/2/04',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: 'Javascript实现一个链表',
	// 	description: '',
	// 	date: '2021/2/03',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: '软件三大原则',
	// 	description: 'DRY、KISS、YAGNI',
	// 	date: '2020/09/09',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: 'Ngix',
	// 	description:
	// 		'“Nginx是一款轻量级的HTTP服务器，采用事件驱动的异步非阻塞处理方式框架，这让其具有极好的IO性能，时常用于服务端的反向代理和负载均衡。”',
	// 	date: '2020/06/15',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'life',
	// 	title: '北京海底捞价格一览表',
	// 	description: '该表时间为2020年6月12日，以当天时间为准。',
	// 	date: '2020/06/12',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: '可选链操作符',
	// 	description:
	// 		'可选链操作符 ?. 可以按照操作符之前的属性是否有效，链式读取对象的属性或者使整个对象链返回 undefined。',
	// 	date: '2020/05/27',
	// 	url: '/guard-against-personal',
	// },
	// {
	// 	type: 'blog post',
	// 	title: 'Git提交的正确姿势',
	// 	description: 'Commit message 包括三个部分：Header、Body、Footer。其中，Header是必须的，Body和Footer可以省略。',
	// 	date: '2020/05/26',
	// 	url: '/guard-against-personal',
	// },
	{
		type: 'blog post',
		title: '本地服务器和浏览器运行html文件的区别',
		description: '浏览器是file协议，本地服务器是http协议。',
		date: '2020/05/22',
		url: '/local-server-and-browser',
	},
	{
		type: 'think',
		title: '警惕个人的政治正确',
		description:
			'在国家和社会层面警惕政治正确思想很重要，但对于我们个人来说，警惕个人内心的所谓政治正确的限制更为重要。',
		date: '2019/11/29',
		url: '/guard-against-personal',
	},
	{
		type: 'leetcode',
		title: 'leetcode-求最大公约数',
		description: '辗转相除法',
		date: '2019/11/05',
		url: '/leetcode-finding-the-greatest',
	},
	{
		type: 'life',
		title: '党和国家领导人北京住宅或官邸',
		description: '目前，党和国家领导人多在北京市及附近地区居住。',
		date: '2019/11/13',
		url: '/party-and-state-leaders-in-beijing',
		pinned: true,
	},
];
